#!/usr/bin/env bash
# Bash script zat transfers file from our client to server
# Requirment :
#    The path to the file to be transferred
#    The IP of the server we want to transfer the file to
#    The username scp connects with
#    The path to the SSH private key that scp uses
#    Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#    scp must transfer the file to the user home directory ~/
#    Strict host key checking must be disabled when using scp
if [ "$#" -lt 3 ];
    then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
