#!/usr/bin/env bash
# Bash script that makes nginx run from the user 'nginx'
pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
chown nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx bash -c 'service nginx start'
